#!/usr/bin/env bash

set -x

rm -rf $HOME/.bashisms
mkdir -p $HOME/.bashisms
cp *.bash $HOME/.bashisms
cp -r ./bin $HOME/.bashisms/bin
cp -r ./bosh_cache $HOME/.bashisms/bosh_cache
if which -s veritas ; then
  veritas completions > $HOME/.bashisms/.veritas_completions.bash
fi