#!/usr/bin/env bash
if [[ -z "$1" ]] || [[ "$1" == "help" ]] ; then
  echo "usage: bosh_ip VM <deployment>"
  echo "returns the ip of the VM using the current deployment unless <deployment> is specified"
  exit 1
fi

export VMS=$1
CURRENT_DEPLOYMENT=${2:-`get_bosh_deployment`}
VMS_FILE="$HOME/.bosh_cache/${CURRENT_DEPLOYMENT}_vms"
IP=`cat $VMS_FILE | ruby -ne 'a = /#{Regexp.escape(ENV["VMS"])}(?:.+?\|){3}(.+?)\|/.match($_); puts a[1].strip if a;'`
if [[ `get_bosh_target` == "warden" ]]; then
  echo $IP.xip.io;
else
  echo $IP;
fi